/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classroom.gui;

import classroom.database.ConnectionDB;
import classroom.modal.Student;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author Flukebregas
 */
public class TE_Create extends javax.swing.JFrame {

    Classroom home = new Classroom();
    int userId = home.userId;
    /**
     * Creates new form TE_Create
     */
    private String name;

    private String details;

    public TE_Create() throws SQLException {
        initComponents();
        getNumStudent();
    }

    public void getNumStudent() throws SQLException {
        int numStudent = 0;
        Connection conn = ConnectionDB.getConnection();
        Statement st = conn.createStatement();
        String sql = "select * from classroom.person where position='STUDENT'";
        st.executeQuery(sql);
        ResultSet rs = st.getResultSet();

        while (rs.next()) {
            numStudent++;
        }
        this.nunStudent.setText(String.valueOf(numStudent));
        conn.close();
    }

    public void getToDB(String sql) throws SQLException {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        desText = new javax.swing.JTextArea();
        nunStudent = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Work");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 190, -1));

        jButton1.setBackground(new Color(0,0,0,0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classroom/gui/deco/sub.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 287, 100, 60));

        jButton2.setBackground(new Color(0,0,0,0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classroom/gui/deco/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 291, 110, 50));

        desText.setColumns(20);
        desText.setRows(5);
        jScrollPane1.setViewportView(desText);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, 160));
        getContentPane().add(nunStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 268, 91, 28));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classroom/gui/deco/TE_CREAW.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(350, 371));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            int check = 0;
            // TODO add your handling code here:
            if (this.nameText.getText().equalsIgnoreCase("") || this.desText.getText().equalsIgnoreCase("") || Integer.decode(this.nunStudent.getText()) == 0) {
                JOptionPane.showMessageDialog(null, "Enter Text Fields or don't have student this your class");
            }
            Connection conn = ConnectionDB.getConnection();
            PreparedStatement ck = conn.prepareStatement("select name"
                    + " from Work where name=?");
            PreparedStatement ps = conn.prepareStatement("INSERT INTO Work"
                    + "(name, description, status, answer, score, tch ,std) VALUES"
                    + "(?,?,?,?,?,?,?)");
            ck.setString(1, name);
            ResultSet ck_result = ck.executeQuery();
            String message = " Are you sure ? ";
            String title = "CONFIRM SEND WORK";
            int chk = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
            if (chk == JOptionPane.YES_OPTION) {
                if (!(ck_result.next())) {
                    ArrayList<Student> list = Student.getAllStudent();
                    for (Student std : list) {
                        System.out.println(std);
                        ps.setString(1, this.nameText.getText());
                        ps.setString(2, this.desText.getText());
                        ps.setInt(3, 0);
                        ps.setString(4, "");
                        ps.setInt(5, 0);
                        ps.setInt(6, TE_Home.tch.getId());
                        ps.setInt(7, std.getId());
                        check = ps.executeUpdate();
                    }
                    if (check == 1) {
                        conn.close();
                        JOptionPane.showMessageDialog(null, "Add work completed.");
                        TE_Home sh = new TE_Home(TE_Home.tch);
                        sh.setVisible(true);
                        this.setVisible(false);
                    } else {
                        conn.close();
                        JOptionPane.showMessageDialog(null, "Error.");
                    }
                } else {
                    // Blank
                }
                conn.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(TE_Create.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            TE_Home tc = new TE_Home(TE_Home.tch);
            tc.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(TE_Create.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TE_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TE_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TE_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TE_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TE_Create().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TE_Create.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea desText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel nunStudent;
    // End of variables declaration//GEN-END:variables
}
